student = User.create(email: 'student@learnhowtoprogram.com', password: 'ilovetolearn')
author = User.create(email: 'author@learnhowtoprogram.com', password: 'ilovetoteach').update_column(:author, true)
chapter = Chapter.create(name: 'Chapter 1', number: 1)
section = Section.create(name: 'Section 1', number: 1, chapter_id: chapter.id)
page = Page.create(title: 'Page 1', body: '<p>I am a page.</p>', number: 1, section_id: section.id)
